// export {registerNewUser} from './registerNewUser'
// export {signInUser} from './signInUser'
export {registerNewProduct} from './registerNewProduct'
export {registerNewOrder} from './registerNewOrder'
export {registerNewAutomaticOrder} from './registerNewAutomaticOrder'
export {editOrder} from './editOrder'
export {editProduct} from './editProduct'
// export {Register} from './register'
export {getProductBySku} from './getProductBySku'
export {getProductById} from './getProductById'
export {getCostumerByPhone} from './getCostumerByPhone'
export {getAllCostumers} from './getAllCostumers'
export {getAllProducts} from './getAllProducts'
export {getData} from './getData'
export {getOrderByHash} from './getOrderByHash'
